[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_WEBPACK_USEPOLLING = "1"
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_BUNDLER = "webpack"
  
[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = [".next/standalone/**"]

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 