[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.x"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  included_files = [".next/standalone/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 