[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_WEBPACK_USEPOLLING = "1"
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  
[[plugins]]
  package = "@netlify/plugin-nextjs" 